apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  labels:
    app.kubernetes.io/name: nexops
    app.kubernetes.io/component: payment-api
spec:
  replicas: {{ .Values.paymentApi.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: nexops
      app.kubernetes.io/component: payment-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nexops
        app.kubernetes.io/component: payment-api
    spec:
      containers:
        - name: payment-api
          image: "{{ .Values.paymentApi.image.repository }}:{{ .Values.paymentApi.image.tag }}"
          imagePullPolicy: {{ .Values.paymentApi.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.paymentApi.service.port }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            {{- toYaml .Values.paymentApi.resources | nindent 12 }}
