apiVersion: v1
kind: Service
metadata:
  name: payment-api
  labels:
    app.kubernetes.io/name: nexops
    app.kubernetes.io/component: payment-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: /metrics
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nexops
    app.kubernetes.io/component: payment-api
  ports:
    - name: http
      port: {{ .Values.paymentApi.service.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: orders-api
  labels:
    app.kubernetes.io/name: nexops
    app.kubernetes.io/component: orders-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8001"
    prometheus.io/path: /metrics
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nexops
    app.kubernetes.io/component: orders-api
  ports:
    - name: http
      port: {{ .Values.ordersApi.service.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: nexops
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nexops
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
