apiVersion: v1
kind: Service
metadata:
  name: payment-api
  namespace: nexops
  labels:
    app.kubernetes.io/name: nexops
    app.kubernetes.io/component: payment-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nexops
    app.kubernetes.io/component: payment-api
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: orders-api
  namespace: nexops
  labels:
    app.kubernetes.io/name: nexops
    app.kubernetes.io/component: orders-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nexops
    app.kubernetes.io/component: orders-api
  ports:
    - name: http
      port: 8001
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: nexops
  labels:
    app.kubernetes.io/name: nexops
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nexops
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
